
namespace Workshop
{
	public class BigClass
	{
		public System.String Property0 { get; set; } 
		public System.String Property1 { get; set; } 
		public System.String Property2 { get; set; } 
		public System.String Property3 { get; set; } 
		public System.String Property4 { get; set; } 
		public System.String Property5 { get; set; } 
		public System.String Property6 { get; set; } 
		public System.String Property7 { get; set; } 
		public System.String Property8 { get; set; } 
		public System.String Property9 { get; set; } 
		public System.String Property10 { get; set; } 
		public System.String Property11 { get; set; } 
		public System.String Property12 { get; set; } 
		public System.String Property13 { get; set; } 
		public System.String Property14 { get; set; } 
		public System.String Property15 { get; set; } 
		public System.String Property16 { get; set; } 
		public System.String Property17 { get; set; } 
		public System.String Property18 { get; set; } 
		public System.String Property19 { get; set; } 
		public System.String Property20 { get; set; } 
		public System.String Property21 { get; set; } 
		public System.String Property22 { get; set; } 
		public System.String Property23 { get; set; } 
		public System.String Property24 { get; set; } 
		public System.String Property25 { get; set; } 
		public System.String Property26 { get; set; } 
		public System.String Property27 { get; set; } 
		public System.String Property28 { get; set; } 
		public System.String Property29 { get; set; } 
		public System.String Property30 { get; set; } 
		public System.String Property31 { get; set; } 
		public System.String Property32 { get; set; } 
		public System.String Property33 { get; set; } 
		public System.String Property34 { get; set; } 
		public System.String Property35 { get; set; } 
		public System.String Property36 { get; set; } 
		public System.String Property37 { get; set; } 
		public System.String Property38 { get; set; } 
		public System.String Property39 { get; set; } 
		public System.String Property40 { get; set; } 
		public System.String Property41 { get; set; } 
		public System.String Property42 { get; set; } 
		public System.String Property43 { get; set; } 
		public System.String Property44 { get; set; } 
		public System.String Property45 { get; set; } 
		public System.String Property46 { get; set; } 
		public System.String Property47 { get; set; } 
		public System.String Property48 { get; set; } 
		public System.String Property49 { get; set; } 

		public System.Int32 Property50 { get; set; } 
		public System.Int32 Property51 { get; set; } 
		public System.Int32 Property52 { get; set; } 
		public System.Int32 Property53 { get; set; } 
		public System.Int32 Property54 { get; set; } 
		public System.Int32 Property55 { get; set; } 
		public System.Int32 Property56 { get; set; } 
		public System.Int32 Property57 { get; set; } 
		public System.Int32 Property58 { get; set; } 
		public System.Int32 Property59 { get; set; } 
		public System.Int32 Property60 { get; set; } 
		public System.Int32 Property61 { get; set; } 
		public System.Int32 Property62 { get; set; } 
		public System.Int32 Property63 { get; set; } 
		public System.Int32 Property64 { get; set; } 
		public System.Int32 Property65 { get; set; } 
		public System.Int32 Property66 { get; set; } 
		public System.Int32 Property67 { get; set; } 
		public System.Int32 Property68 { get; set; } 
		public System.Int32 Property69 { get; set; } 
		public System.Int32 Property70 { get; set; } 
		public System.Int32 Property71 { get; set; } 
		public System.Int32 Property72 { get; set; } 
		public System.Int32 Property73 { get; set; } 
		public System.Int32 Property74 { get; set; } 
		public System.Int32 Property75 { get; set; } 
		public System.Int32 Property76 { get; set; } 
		public System.Int32 Property77 { get; set; } 
		public System.Int32 Property78 { get; set; } 
		public System.Int32 Property79 { get; set; } 
		public System.Int32 Property80 { get; set; } 
		public System.Int32 Property81 { get; set; } 
		public System.Int32 Property82 { get; set; } 
		public System.Int32 Property83 { get; set; } 
		public System.Int32 Property84 { get; set; } 
		public System.Int32 Property85 { get; set; } 
		public System.Int32 Property86 { get; set; } 
		public System.Int32 Property87 { get; set; } 
		public System.Int32 Property88 { get; set; } 
		public System.Int32 Property89 { get; set; } 
		public System.Int32 Property90 { get; set; } 
		public System.Int32 Property91 { get; set; } 
		public System.Int32 Property92 { get; set; } 
		public System.Int32 Property93 { get; set; } 
		public System.Int32 Property94 { get; set; } 
		public System.Int32 Property95 { get; set; } 
		public System.Int32 Property96 { get; set; } 
		public System.Int32 Property97 { get; set; } 
		public System.Int32 Property98 { get; set; } 
		public System.Int32 Property99 { get; set; } 

	}
}